### ISSUE TITLE
Style polish for 0.0.1

### ISSUE THREAD

**Issue by cryptoquick** [FuzzrNet/Fuzzr#18]
- [x] Border radius should be 1.0
- [x] Page selector spacing between buttons with columns
- [x] Disabled state styles (black text, no border)
- [x] Active state styles (black border)
- [x] All non-testing page buttons that are currently in the `hidden` vec should be displayed by default, but disabled

**Comment by kn0wmad** [comment]
Is it apt to have the disabled buttons carry a 'Disabled' PageType, which contains nothing?  Or is there a more idiomatic approach

**Comment by cryptoquick** [comment]
I think it'll be best to keep the PageType the same and instead use a separate boolean property.

**Comment by kn0wmad** [comment]
Thanks.  I attempted to go down this path and somehow ended up going down both.  I'll get your thoughts on it if it doesn't work out
