### ISSUE TITLE
No masters

### ISSUE THREAD

**Issue by cryptoquick** [FuzzrNet/Fuzzr#24]
Rename master branch to main and change it to the default branch in GitHub settings

**Comment by nuke-web3** [comment]
new `main` branch, default in settings.

HEAD points to PR #43 

Note @cryptoquick and @kn0wmad you need to change your git settings to reflect this, checkout main.

once you do that, we can delete `master` 
🚫 👑

**Comment by kn0wmad** [comment]
I committed to my working branch, checked out and pulled master, checked out main, pulled again.  I'm guessing this is all I needed to do?

**Comment by nuke-web3** [comment]
Should be set! Just delete your local masters 😈 :
```
git branch -d master
```
to delete from github (or any remote, change origin)
```
git branch -d origin master
```
