### ISSUE TITLE
Add a light/dark mode

### ISSUE THREAD

**Issue by kn0wmad** [FuzzrNet/Fuzzr#4]
Only work on this if you have no other things to work on. It'll be really nice to have when we go to show off our work, but it's more impressive that we have actual features.

- [x] Learn how to do a stylesheet. There are examples for this exact feature (night/dark) in Iced: https://github.com/hecrj/iced/search?q=dark
- [x] Add a toggle button to all pages
- [x] Reverse color-scheme on button press
- [x] Change PageSelector to Toolbar
- [x] Should apply to all elements (buttons, etc)

**Comment by kn0wmad** [comment]
Considering renaming the PageSelector (Controls/PageControls/Menu?) as it might be the place to add additional functions, such as the night/dark toggle.  Thoughts?

**Comment by cryptoquick** [comment]
Good idea! How about "Toolbar" ?

**Comment by kn0wmad** [comment]
I dig toolbar... it's like a bar, that serves tools

**Comment by cryptoquick** [comment]
Stop me if you've heard this one.

Two tools walk in to a bar.

One tool asks to see the menu.

The bartender says the menus are upstairs.
