### ISSUE TITLE
Design mock-up (subject to heavy change)

### ISSUE THREAD

**Issue by kn0wmad** [FuzzrNet/Fuzzr#42]
![mock-up](https://user-images.githubusercontent.com/39687477/102379541-2e4d8f80-3f84-11eb-9209-1bcfee0515f7.jpeg)

*Wanted this to be a note, but image support was not available

**Comment by nuke-web3** [comment]
ah yes, each project page is directly linked to an issue - it's just a GUI for tracking issues basically. the right side bar has a setting to add this to a board's card @kn0wmad 

Closes #43

**Comment by nuke-web3** [comment]
In fact, it is: 
![image](https://user-images.githubusercontent.com/35669742/102534340-d38b6500-4063-11eb-8895-15a5ca6d22e3.png)
Was this what you were after?

**Comment by kn0wmad** [comment]
You see on the left under 'issue proposed' where there's a note that isn't an issue - that's what I was going for. Although I don't think it matters
