### ISSUE TITLE
Tasks for ETH Denver

### ISSUE THREAD

**Issue by cryptoquick** [FuzzrNet/Fuzzr#96]
I've been meaning to post this, and I'm not sure how much time I'll have for this, so here's what I had planned:

- Possible ETH Denver tasks
    - Image thumbnail selection
    - Publish from thumbnail
    - Text content thumbnails
    - HTML rendering of the image thumbnail screen
    - Warp Server
    - WASM frontend for Start9 Embassy
    - Content Type Filter for selecting text documents
    - ~~Markdown rendering in Iced~~

I haven't really had any time for Fuzzr and that makes me a little grumpy, but... Sometimes work is work.

**Comment by kn0wmad** [comment]
The only thing I have a clue about is a Warp Server, so I'm going to give it a shot... hope work is going well :)

**Comment by cryptoquick** [comment]
We won't be supporting text documents, only images for now. Another platform will be used for the "FuzzrWeb"
